[package]
name = "makepad-trapezoidator"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Polygon trapezoidator"
license = "MIT"

[dependencies]
makepad-geometry = { path = "../geometry", version = "0.1" }
makepad-internal-iter = { path = "../internal_iter", version = "0.1" }
makepad-path = { path = "../path", version = "0.1" }
