[package]
name = "makepad-hub"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad hub"
license = "MIT"

[dependencies.makepad-microserde]
path="../../render/microserde"

[dependencies.makepad-http]
path="../http"
