[package]
name = "bare_example_wasm"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.bare_example_app]
path="../app"

[dependencies.makepad-render]
path="../../../render"
version="0.2"