[package]
name = "makepad-detok-derive"
version = "0.2.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad detok derive"
license = "MIT"

[lib]
proc-macro = true

[dependencies]


