[package]
name = "makepad-draw-derive"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad draw derive"
license = "MIT"

[lib]
proc-macro = true

[dependencies]


