 [package]
name = "makepad-worlds"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad worlds"
license = "MIT"

[dependencies.makepad-widget]
path="../widget"

[dependencies.makepad-render]
path="../render"


