[package]
name = "threed_example"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]

[dependencies.makepad-render]
path="../../render"

[dependencies.threed_example_app]
path="./app"
